# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.trainART <- function(net, x) {
    invisible(.Call('_rART_trainART', PACKAGE = 'rART', net, x))
}

.predictART <- function(net, id, x) {
    .Call('_rART_predictART', PACKAGE = 'rART', net, id, x)
}

.ART <- function(numFeatures, num = 1L, vigilance = 0.75, learningRate = 1.0, categorySize = 100L, maxEpochs = 20L) {
    .Call('_rART_newART', PACKAGE = 'rART', numFeatures, num, vigilance, learningRate, categorySize, maxEpochs)
}

.ARTMAP <- function(numFeatures, vigilance = 0.75, learningRate = 1.0, categorySize = 100L, maxEpochs = 20L, simplified = FALSE) {
    .Call('_rART_newARTMAP', PACKAGE = 'rART', numFeatures, vigilance, learningRate, categorySize, maxEpochs, simplified)
}

.trainARTMAP <- function(net, x, labels = NULL, dummyLabels = NULL) {
    invisible(.Call('_rART_trainARTMAP', PACKAGE = 'rART', net, x, labels, dummyLabels))
}

.predictARTMAP <- function(net, x, labels = NULL, dummyLabels = NULL, test = FALSE) {
    .Call('_rART_predictARTMAP', PACKAGE = 'rART', net, x, labels, dummyLabels, test)
}

.TopoART <- function(numFeatures, num = 2L, vigilance = 0.9, learningRate1 = 1.0, learningRate2 = 0.6, tau = 100L, phi = 6L, categorySize = 200L, maxEpochs = 20L) {
    .Call('_rART_TopoART', PACKAGE = 'rART', numFeatures, num, vigilance, learningRate1, learningRate2, tau, phi, categorySize, maxEpochs)
}

.topoTrain <- function(net, x, labels = NULL) {
    invisible(.Call('_rART_topoTrain', PACKAGE = 'rART', net, x, labels))
}

.topoPredict <- function(net, id, x) {
    .Call('_rART_topoPredict', PACKAGE = 'rART', net, id, x)
}

linkClusters <- function(edges, nodes) {
    .Call('_rART_linkClusters', PACKAGE = 'rART', edges, nodes)
}

.encodeNumericLabel <- function(labels, code) {
    .Call('_rART_encodeNumericLabel', PACKAGE = 'rART', labels, code)
}

.encodeStringLabel <- function(labels, code) {
    .Call('_rART_encodeStringLabel', PACKAGE = 'rART', labels, code)
}

