# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.trainART <- function(net, x) {
    invisible(.Call('_rART_train', PACKAGE = 'rART', net, x))
}

.predictART <- function(net, id, x) {
    .Call('_rART_predict', PACKAGE = 'rART', net, id, x)
}

.ART <- function(dimension, num = 1L, vigilance = 0.75, learningRate = 1.0, categorySize = 100L, maxEpochs = 20L) {
    .Call('_rART_newART', PACKAGE = 'rART', dimension, num, vigilance, learningRate, categorySize, maxEpochs)
}

linkClusters <- function(edges, nodes) {
    .Call('_rART_linkClusters', PACKAGE = 'rART', edges, nodes)
}

.encodeNumericLabel <- function(labels, code) {
    .Call('_rART_encodeNumericLabel', PACKAGE = 'rART', labels, code)
}

.encodeStringLabel <- function(labels, code) {
    .Call('_rART_encodeStringLabel', PACKAGE = 'rART', labels, code)
}

